[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-reenix.json"

[target.x86_64-reenix]
rustflags = ["-C", "link-args=-Tsrc/linker.ld", "-C", "link-args=-n"]
runner = "scripts/reenix -d"
