#!/bin/bash
# Move the executable to the GRUB iso directory
cp target/x86_64-reenix/debug/reenix iso/boot

# Rename the executable
mv iso/boot/reenix iso/boot/reenix.bin

Create the iso
grub-mkrescue -o iso/reenix.iso iso

xterm -geometry 100x30+50+50 -bg black -fn 10x20 \
    -title "Reenix Serial" \
    -e "qemu-system-x86_64 -cdrom iso/reenix.iso -k en-us -boot order=dca -vga std -machine q35 -serial stdio"